const assert=require('node:assert/strict'),E=require('../dist/core/engine.js');
const D=require('../dist/data/fighters.js').fighterDefinitions.celeste_proto,S=require('../dist/data/celesteSpatial.js').CELESTE_SPATIAL_SCALE;
const fresh=(x=0,y=200)=>E.createMatch(42,{p1Kind:'celeste_proto',p2Kind:'celeste_proto',p1X:x*S,p2X:y*S});
const run=(s,n,fn=()=>({}))=>{for(let i=0;i<n;i++)E.tick(s,fn(i));return s};
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const air=(s,id='p1',y=-100)=>{Object.assign(s.fighters[id],{grounded:false,y:y*S,vy:-10*S,phase:'jump',phaseTick:0,airActionsRemaining:5,airDashesRemaining:1});return s};
const cases=[['ovation_staccato','light',{}],['ovation_procession','medium',{}],['ovation_fortissimo','heavy',{}],['quickstep_beat','light',{right:true}],['crescendo_slash','medium',{right:true}],['curtain_call','heavy',{right:true}],['waltz_retreat','light',{left:true}],['reversal_measure','medium',{left:true}],['broken_tempo','heavy',{left:true}],['encore_near','light',{down:true}],['encore_reach','medium',{down:true}],['encore_balcony','heavy',{down:true}],['rising_note','light',{up:true}],['ascending_aria','medium',{up:true}],['grand_crescendo','heavy',{up:true}]];
for(const[id,button,dir]of cases){const s=fresh();E.tick(s,{p1:{special:true,[button]:true,...dir}});assert.equal(s.fighters.p1.currentAttack,id);run(s,140);assert.equal(s.fighters.p1.currentAttack,null,id);}
close(D.movement.gravity,1.05*S);close(D.attacks.grand_crescendo.hitboxes[0].rect.h,140*S);
assert.deepEqual([D.attacks.grand_crescendo.startup,D.attacks.grand_crescendo.active,D.attacks.grand_crescendo.recovery,D.attacks.grand_crescendo.hitboxes[0].damage],[23,5,34,84]);
for(const [button,startup,damage]of [['light',14,34],['medium',20,44],['heavy',28,64]]){const s=fresh(0,150);E.tick(s,{p1:{special:true,[button]:true}});run(s,startup-2);assert.equal(s.projectiles?.length??0,0);E.tick(s);assert.equal(s.projectiles.length,1);assert.equal(s.fighters.p1.celeste.solCooldown,45);run(s,50);assert.equal(s.fighters.p2.health,880-damage);}
for(const facing of [1,-1]){const s=fresh(-100*facing,150*facing),f=s.fighters.p1,origin=f.x;E.tick(s,{p1:{special:true,heavy:true,[facing===1?'right':'left']:true}});run(s,9);close(f.x,origin);run(s,14);close(f.x-origin,140*S*facing);assert.equal(f.phaseTick,24);assert.equal(f.celeste.faSpent,true);}
const shield=fresh(0,55);E.tick(shield,{p1:{special:true,left:true,medium:true}});run(shield,5);E.tick(shield,{p2:{light:true}});run(shield,3);assert.equal(shield.fighters.p1.health,880);assert.equal(shield.fighters.p1.celeste.guardSpent,true);assert.equal(shield.fighters.p2.tensionEarned,0);
const trap=fresh(0,85);E.tick(trap,{p1:{special:true,down:true,light:true}});run(trap,25);assert.equal(trap.projectiles[0].ageTicks,0);run(trap,59);assert.equal(trap.fighters.p2.health,880);E.tick(trap);assert.equal(trap.fighters.p2.health,840);
const trade=fresh(0,85);E.tick(trade,{p1:{special:true,down:true,light:true}});run(trade,81);trade.fighters.p2.x=55*S;E.tick(trade,{p2:{light:true}});run(trade,3);assert.equal(trade.fighters.p2.health,880);assert.ok(trade.fighters.p1.health<880);assert.equal(trade.projectiles.length,0);
const descant=air(fresh(),'p1',-40);descant.fighters.p1.vy=-18*S;E.tick(descant,{p1:{special:true,medium:true}});run(descant,17);assert.equal(descant.projectiles.length,1);close(descant.projectiles[0].velocityY,5*S);
const low=air(fresh(),'p1',-25);low.fighters.p1.vy=0;E.tick(low,{p1:{special:true,light:true}});for(let i=0;i<20&&low.fighters.p1.phase!=='landing';i++)E.tick(low);assert.equal(low.fighters.p1.phase,'landing');const x=low.fighters.p1.x,remaining=low.fighters.p1.celesteLandingRecovery;assert.ok(remaining>10);for(let i=0;i<remaining;i++){E.tick(low);close(low.fighters.p1.x,x);assert.equal(low.fighters.p1.vx,0);}
const bounce=air(air(fresh(0,55),'p1',-40),'p2',-40);bounce.fighters.p1.vy=bounce.fighters.p2.vy=-18*S;bounce.fighters.p2.hitstun=90;E.tick(bounce,{p1:{special:true,heavy:true}});for(let i=0;i<35&&!bounce.fighters.p1.attackConnected;i++)E.tick(bounce);const a=bounce.fighters.p1,d=bounce.fighters.p2;assert.equal(d.health,810);assert.equal(a.juggleSpent,3);assert.ok(d.celesteBounce);const checkpoint=E.saveSnapshot(bounce),ledger=[a.comboCount,a.comboDamage,a.juggleSpent,d.hitCountTaken];let bounced=false;for(let i=0;i<80;i++){const pending=!!d.celesteBounce;E.tick(bounce);if(pending&&!d.celesteBounce&&d.vy<0){close(d.vy,-12*S);bounced=true;break;}}assert.ok(bounced);assert.deepEqual([a.comboCount,a.comboDamage,a.juggleSpent,d.hitCountTaken],ledger);
const burst=E.restoreSnapshot(checkpoint);burst.fighters.p2.burst=100;while(burst.fighters.p2.hitstop)E.tick(burst);E.tick(burst,{p2:{burst:true}});assert.equal(burst.fighters.p2.celesteBounce,undefined);
for(const block of [false,true]){const s=fresh();s.fighters.p1.tension=100;E.tick(s,{p1:{ultimate:true},p2:{block}});assert.equal(s.fighters.p1.currentAttack,'octava');assert.equal(s.fighters.p1.tension,0);run(s,26,()=>({p2:{block}}));assert.equal(s.fighters.p2.health,880);E.tick(s,{p2:{block}});assert.equal(s.fighters.p2.health,block?880:655);s.fighters.p1.tension=100;E.tick(s,{p1:{romanCancel:true},p2:{block}});assert.equal(s.fighters.p1.romanCancelCount,0);run(s,100,()=>({p2:{block}}));assert.equal(s.fighters.p2.health,block?880:655);}
const poor=fresh();poor.fighters.p1.tension=99;E.tick(poor,{p1:{ultimate:true}});assert.equal(poor.fighters.p1.currentAttack,null);
for(const command of [{ultimate:true},{special:true,up:true,heavy:true}]){const s=fresh(0,55);s.fighters.p1.tension=s.fighters.p2.tension=100;const copy=E.restoreSnapshot(s);for(let i=0;i<160;i++){const input=i===0?{p1:command,p2:command}:{};E.tickWithFighterOrder(s,input,['p1','p2']);E.tickWithFighterOrder(copy,input,['p2','p1']);assert.deepEqual(s,copy);}}
console.log('PASS main182 Celeste command lifecycles, scale, SOL/FA/LA/TI, air landing, Reprise ledger, Octava and deterministic replay');

// Real jump input retains enough airtime for all three aerial special releases.
for(const [button,id,startup]of [['light','strobe_air_waltz',4],['medium','ovation_descant',18],['heavy','finale_reprise',20]]){const s=fresh();E.tick(s,{p1:{up:true}});while(s.fighters.p1.grounded)E.tick(s);E.tick(s,{p1:{special:true,[button]:true}});assert.equal(s.fighters.p1.currentAttack,id);run(s,startup-1);assert.equal(s.fighters.p1.grounded,false);assert.equal(s.fighters.p1.phase,'attack');if(button==='medium')assert.equal(s.projectiles.length,1);}
console.log('PASS genuine jump inputs reach all three aerial specials before landing');
