const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {compileFromPath}=require('./production_contracts');
const {fighterDefinitions}=require('../dist/data/fighters');
const {sampleAuthoredHop}=require('../dist/core/engine');
const root=path.resolve(__dirname,'..'),repo=path.resolve(root,'../..');
const base=path.join(root,'content-source/characters/lamuh-legacy-v2'),out=path.join(base,'heaven-splitter-packages');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')), hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex').toUpperCase();
const write=(p,v)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');};
const uri=p=>'repo://'+path.relative(repo,p).replaceAll('\\','/');
const reportPath=path.join(repo,'tools/nga-forge/review/lamuh-legacy-v2-heaven-splitter-v1/normalization.report.json'),report=read(reportPath);
const reviewPath=path.join(root,'public/lamuh-legacy-v2/review-data.json'),review=read(reviewPath);
const idle=review.movementModernization.states.idle.frames[0];
const heavyReportPath=path.join(repo,'tools/nga-forge/review/lamuh-legacy-v2-heaven-splitter-v1/heavy-v2.normalization.report.json');
const heavy=fs.existsSync(heavyReportPath)?read(heavyReportPath):null;
const auraReportPath=path.join(repo,'tools/nga-forge/review/lamuh-legacy-v2-heaven-splitter-v1/heavy-authored-aura-v3.report.json');
const aura=heavy&&fs.existsSync(auraReportPath)?read(auraReportPath):null;
const redrawReportPath=path.join(repo,'tools/nga-forge/review/lamuh-legacy-v2-heaven-heavy-aura-redraw-v4/normalization.report.json');
const redraw=heavy&&fs.existsSync(redrawReportPath)?read(redrawReportPath):null;
if(redraw){const p=path.join(base,'records/heaven-heavy-v3.aura-redraw-request.json');if(!fs.existsSync(p))write(p,{decision:'REJECTED_FOR_MOTION_REVISION',userInput:'redo the spritesheet with the proper surrounding aura',scope:'Heaven Splitter Heavy aura artwork',previous:review.heavenSplitterFamily.variants.heavy,candidateOnly:true,deployable:false});}
if(heavy){
 const rejectionPath=path.join(base,'records/heaven-heavy-v1.extended-light.rejection.json');
 if(!fs.existsSync(rejectionPath))write(rejectionPath,{decision:'REJECTED_FOR_MOTION_REVISION',userInput:'THE HEAVY  animation should be more cinematic for the move not just an extended light. it shouuld feel more powerful',date:'2026-09-05',scope:'Heaven Splitter Heavy presentation only',previous:review.heavenSplitterFamily?.variants.heavy||null,retained:['Light/Medium frames','Heavy 14/6/33 timing','one hit','80 damage','simulation hop'],next:'distinct heavy windup, extension, recovery and cinematic presentation'});
}
const template=read(path.join(base,'celestial-palm-packages/light/animation.package.json'));
const status='awaiting_human_heaven_splitter_family_review';
const warning=['One near-arm uppercut throughout; modernized from legacy far-arm uppercut, not exact striking-arm preservation.','Original seven-pose rising arc remains protected; legacy airborne scale shrink and detached sandal were not reproduced.','Authored hop and vulnerable recovery belong to simulation; no invulnerability, extra hit or renderer-driven height.','Adult identity, alpha, physical contact and landing require human playback judgment.','B is gameplay-aligned. A/C retime anticipation/recovery for visual comparison only.'];
const approvalPath=path.join(out,'records/human-review.pending.json'),provenancePath=path.join(out,'records/provenance.json'),registrationPath=path.join(out,'records/registration.json');
write(approvalPath,{state:'pending',approvedAt:null,approvedBy:null,candidateOnly:true,deployable:false,remainingReview:warning});
const provenance={...template.provenance,createdAt:new Date(fs.statSync(reportPath).mtime).toISOString(),references:[uri(path.join(root,'public',idle.publicPath)),uri(path.join(root,'public/lamuh-legacy-v2/atlases/lamuh_sheet_5_specials_atlas.png'))],cleanupOperations:['edge_connected_checker_cutout','exterior_matte_unmix','constant_anatomical_scale','manual_pelvis_registration','virtual_ground_for_air_poses','approved_idle_endpoints'],revisionChain:['V1_HEAVEN_SPLITTER','V2_NEAR_ARM_UPPERCUT_CANDIDATE'],humanApproval:{state:'pending',approvedAt:null,approvedBy:null}};
if(heavy){provenance.references.push(uri(path.join(repo,'tools/nga-forge/review/lamuh-legacy-v2-heaven-splitter-v1/raw/heavy-windup-landing.png')),uri(path.join(repo,'tools/nga-forge/review/lamuh-legacy-v2-heaven-splitter-v1/raw/heavy-release.png')));provenance.revisionChain.push('H_V2_DISTINCT_CINEMATIC_BODY');}
if(aura){provenance.references.push(uri(auraReportPath));provenance.cleanupOperations.push('native_aura_export_pose_aligned_preserved_opaque_body');provenance.revisionChain.push('H_V3_AURA_IN_INDIVIDUAL_SOURCE_FRAMES');}
if(redraw){provenance.references.push(uri(redrawReportPath),...['raw-aura-redraw.png','raw-aura-magenta.png','prompt.md'].map(f=>uri(path.join(path.dirname(redrawReportPath),f))));provenance.cleanupOperations.push('generated_surrounding_aura_identity_edit','magenta_matte_unmix','audited_whitespace_slicing_preserved_absolute_root');provenance.revisionChain.push('H_V4_REDRAWN_SURROUNDING_AURA');}
write(provenancePath,provenance);write(registrationPath,{...report,heavyV2:heavy,authoredAuraV3:aura,redrawnAuraV4:redraw,notes:warning});
const standardSequence=[idle,...[1,2,3,5,6,7,8,9,10].map(i=>report.frames[i]),idle];
const exposures={light:[2,3,2,4,4,3,3,3,4,4,4],medium:[3,5,2,5,6,4,4,4,4,3,3],heavy:[4,8,2,6,7,5,6,5,4,3,3]};
const family={schemaVersion:'1.0.0',status,candidateOnly:true,deployable:false,variants:{},humanApproval:{family:null,light:null,medium:null,heavy:null},contactSheets:[report.contactSheetPublicPath],reviewNotes:warning,normalizationReport:uri(reportPath)};
if(heavy){family.contactSheets.push(aura?aura.contactSheetPublicPath:'/lamuh-legacy-v2/heaven-heavy-v2/heavy-active-numbered-contact-sheet.png');family.heavyCinematicRevision={version:aura?3:2,status:'pending_human_review',normalizationReport:uri(heavyReportPath),authoredAuraReport:aura?uri(auraReportPath):null,runtimeAuraOverlay:!aura,combatChanged:false,lightMediumChanged:false,distinctHeavyBody:true,cameraImpulseMaxPixels:6,noZoom:true,oneHit:true};}
if(redraw){family.contactSheets[1]='/lamuh-legacy-v2/heaven-heavy-aura-redraw-v4/heavy-redrawn-aura-active-contact-sheet.png';family.heavyCinematicRevision={...family.heavyCinematicRevision,version:4,authoredAuraReport:uri(redrawReportPath),runtimeAuraOverlay:false,artRedrawn:true,pixelExactBodyPreservation:false};}
for(const strength of ['light','medium','heavy']){
 const id='heaven_splitter_'+strength,attackId='legacy_'+id,attack=fighterDefinitions.lamuh_legacy_v2.attacks[attackId],hit=attack.hitboxes[0];
 if(!attack.authoredHop)throw new Error('Build simulation before Heaven content');
 const isCinematic=strength==='heavy'&&!!heavy;
 const bodySequence=isCinematic?[idle,...[1,2].map(i=>heavy.families.windup.frames[i]),...heavy.families.release.frames,...[8,9,10,11].map(i=>heavy.families.windup.frames[i]),idle]:standardSequence;
 const sequence=isCinematic&&redraw?bodySequence.map((f,i)=>({...((i>=3&&i<=8)?redraw.frames[i-3]:f),auraBaked:true})):isCinematic&&aura?aura.frames.map((f,i)=>{
  if(f.bodyOnlySha256!==bodySequence[i].sha256)throw new Error('Authored aura body source is stale; rebake Heavy');
  return i===0||i===aura.frames.length-1?idle:f;
 }):bodySequence;
 const roles=['approved idle entry','heavy weight sink','deep shoulder wind-back','compressed near-arm coil','fist rising connector','single powerful uppercut CONTACT','full extension and coat drag','apex elbow release','guarded knee gather','feet unfold for heavy landing','deep two-foot landing compression','weight settles and guard returns','coat-lag ready recovery','approved idle endpoint'];
 const exp=isCinematic?[2,3,4,3,2,6,7,3,5,8,4,3,2,1]:exposures[strength],contactIndex=isCinematic?5:3,total=attack.startup+attack.active+attack.recovery;
 if(exp.reduce((a,b)=>a+b,0)!==total||exp.slice(0,contactIndex).reduce((a,b)=>a+b,0)!==attack.startup)throw new Error('Authored timing mismatch');
 const pathAt=t=>({x:Math.max(0,Math.min(t-attack.rootMotion.start+1,attack.rootMotion.end-attack.rootMotion.start+1))*attack.rootMotion.velocity,y:sampleAuthoredHop(attack.authoredHop,t).y});
 let tick=0;const frames=sequence.map((source,index)=>{const f={...source,index,role:isCinematic?roles[index]:index===0?'approved idle entry':index===sequence.length-1?'approved idle endpoint':source.role,contact:index===contactIndex,visibleImpact:index===contactIndex,authoredWorldRootOffset:pathAt(tick)};tick+=exp[index];return f;});
 const timing={};for(const [candidate,delta] of [['A',-2],['B',0],['C',2]]){const e=[...exp];e[isCinematic?2:1]+=delta;e[isCinematic?10:e.length-1]+=delta;timing[candidate]={label:candidate==='B'?'RECOMMENDED_GAMEPLAY_ALIGNED':candidate==='A'?'COMPACT_V2_VARIANT':'HEAVIER_V2_ALTERNATE',phaseTicks:{startup:attack.startup+delta,active:attack.active,recovery:attack.recovery+delta},durationTicks:total+2*delta,exposureTicks:e,preservesSourceFrameOrder:true,duplicateMeaninglessFrames:false};}
 const c=structuredClone(review.celestialPalmFamily.variants.light);
 for(const field of ['approvalReceipt','approvalScope','approvalBoundary','humanApproval','approvedAt','approvedBy'])delete c[field];
 c.status=status;c.v1={sourceFrameCount:7,historicalDurationTicks:36,reconstructedExposureTicks:[5,5,5,5,5,5,6],root:{x:224,y:382},visibleBounds:report.v1Frames.map(f=>f.visibleBounds),bodyCenters:report.v1Frames.map(f=>f.bodyCenter),contactFrame:1,exactContactTick:null,note:'Legacy36-tick evidence; exact pose exposures/contact unrecoverable. Seven protected poses shown with reconstructed holds.'};
 c.v2={canvas:report.canvas,root:report.root,rootPath:frames.map(f=>f.root),authoredWorldRootPath:Array.from({length:total},(_,t)=>pathAt(t)),frames,contactFrame:contactIndex,contactFrames:[contactIndex],contactPresentation:{publicPath:frames[contactIndex].publicPath,sha256:frames[contactIndex].sha256,bodyOnlyOnWhiff:true,bodyOnlyForAllOutcomes:true,vfxEnabled:false,allowedOutcomes:[],separationStatus:'opaque_body_separate_phase_arc_and_authoritative_contact_feedback'},singleSequenceScale:report.scale,perFrameRescale:false,visualRecentering:false,placementPolicy:report.registration,visibleImpactCount:1,gameplayHitCount:1,releaseSocket:isCinematic?{x:890,y:420}:{x:865,y:390}};
 if(isCinematic){c.v2.sourceArtCameraCorrections=[1,.8];c.v2.cinematicRevision={version:2,bodyPerformance:'deep coil, rising-fist connector, full uppercut extension, guarded gather, heavy two-foot catch',camera:'short confirmed-hit impulse, no body rescale or zoom',contactOnlyCamera:true,aura:{source:'src/lamuhlegacy/heavenSplitter.ts',layer:'behind_opaque_body',anchor:'actor_root_and_rising_fist',followsActor:true,mirrorsAttackFacing:true,startTick:9,fullExposureTicks:[14,19],endTickExclusive:30,alphaRange:[0,1],palette:'cyan_gold',hitstopFreezes:true,addsHits:false}};}
 if(isCinematic&&aura){c.v2.auraBakedIntoFrames=true;c.v2.cinematicRevision.version=3;c.v2.cinematicRevision.aura={...c.v2.cinematicRevision.aura,source:uri(auraReportPath),layer:'authored_source_frame_pixels',runtimeOverlay:false,sourcePoseIndices:[3,4,5,6,7],fullExposureTicks:[14,26],fadePoseIndex:7,bodyOnlyFallbackRetained:true};}
 if(isCinematic&&(aura||redraw)){c.v2.contactPresentation.bodyOnlyForAllOutcomes=false;c.v2.contactPresentation.bodyOnlyOnWhiff=false;c.v2.contactPresentation.classification='authored_body_plus_motion_aura';c.v2.contactPresentation.separationStatus='authored_body_aura_pixels_separate_hit_confirm_feedback';}
 if(isCinematic&&redraw){c.v2.auraBakedIntoFrames=true;c.v2.cinematicRevision.version=4;c.v2.cinematicRevision.artRedrawn=true;c.v2.cinematicRevision.pixelExactBodyPreservation=false;c.v2.cinematicRevision.aura={...c.v2.cinematicRevision.aura,source:uri(redrawReportPath),layer:'redrawn_surrounding_aura_in_source_art',runtimeOverlay:false,sourcePoseIndices:[3,4,5,6,7,8],endTickExclusive:35,fadePoseIndices:[7,8],bodyOnlyFallbackRetained:true,bodyOnlyComparison:'previous clean poses, not pixel-identical aura removal'};}
 c.timingCandidates=timing;c.impactCandidates=Object.fromEntries([['I1',-1],['I2',0],['I3',1]].map(([i,d])=>[i,{label:i==='I2'?'AUTHORED':'VISUAL_IMPACT_COMPARISON',hitstopTicks:hit.hitstop+d,contactExposureDelta:0,recoilExposureDelta:0,recoveryExposureDelta:0}]));
 c.recommendedTimingCandidate='B';c.recommendedImpactCandidate='I2';family.variants[strength]=c;
 const historical={durationTicks:36,exposureTicks:[5,5,5,5,5,5,6],durationEvidence:'historical_v1_c032',exposureEvidence:'RECONSTRUCTION: exact original exposures not recoverable',note:c.v1.note};
 review.timingCandidates.moves=review.timingCandidates.moves.filter(m=>m.moveId!==id).concat({moveId:id,sourceFrameCount:7,authoredFrameCount:frames.length,contactSourceFrames:[contactIndex],v1Historical:historical,candidates:timing,recommendedCandidate:'B',humanReviewStatus:status,note:warning.join(' ')});
 const pack=structuredClone(template);pack.id=id;pack.simulationLength=total;pack.provenance=provenance;
 pack.sourceFrames=frames.map((f,i)=>({id:id+'_frame_'+i,sourceUri:uri(f.publicPath.includes('heaven-heavy-aura-redraw-v4')?path.join(base,'heaven-heavy-aura-redraw-frames-v4',path.basename(f.publicPath)):f.publicPath.includes('heaven-heavy-aura-v3')?path.join(base,'heaven-heavy-aura-frames-v3',path.basename(f.publicPath)):f.publicPath.includes('heaven-heavy-v2')?path.join(base,'heaven-heavy-frames-v2',path.basename(f.publicPath)):f.publicPath.includes('heaven-splitter-v1')?path.join(base,'heaven-splitter-frames-v1',path.basename(f.publicPath)):path.join(root,'public',f.publicPath)),width:2048,height:1536,sha256:f.sha256,approvalUri:uri(approvalPath),provenanceUri:uri(provenancePath),metadataUri:uri(registrationPath)}));
 let cursor=0;pack.exposures=exp.map((duration,i)=>{const e={sourceFrameId:pack.sourceFrames[i].id,start:cursor,duration};cursor+=duration;return e;});
 pack.phases={anticipation:[],startup:[{start:0,end:attack.startup-1}],active:[{start:attack.startup,end:attack.startup+attack.active-1}],impact:[],followThrough:[],recovery:[{start:attack.startup+attack.active,end:total-1}]};
 pack.anchors=pack.exposures.map(e=>({frame:e.start,sourceFrameId:e.sourceFrameId,root:report.root,feet:report.root,nearFoot:report.root,farFoot:report.root,effect:c.v2.releaseSocket,groundingContract:'pelvis_registered_virtual_ground_no_airborne_foot_plant_claim'}));
 pack.groundingTrack=pack.sourceFrames.map(f=>({sourceFrameId:f.id,root:report.root,nearFoot:report.root,farFoot:report.root,nearFootRole:'virtual_ground_reference_not_measured_foot',farFootRole:'virtual_ground_reference_not_measured_foot',projectedGroundPlaneY:1360,contractVersion:'pelvis_virtual_ground_v1'}));
 pack.combatTrack={startup:attack.startup,active:attack.active,recovery:attack.recovery,damage:hit.damage,hitstop:hit.hitstop,hitstun:hit.hitstun,blockstun:hit.blockstun,boxes:Array.from({length:attack.active},(_,n)=>({frame:attack.startup+n,kind:'hit',x:hit.rect.x,y:hit.rect.y,width:hit.rect.w,height:hit.rect.h})),cancelWindows:[],timingAuthorship:{...template.combatTrack.timingAuthorship,authoredTotalDuration:total},selfMotionTrack:{owner:'deterministic_simulation',attackId,hop:attack.authoredHop,rootMotion:attack.rootMotion,interruption:'handoff_current_position_and_velocity_to_physics',hitstopFreezes:true}};
 pack.landing=[{start:attack.authoredHop.landTick,end:total-1,result:'special_landing'}];
 pack.presentationTrack=[{index:0,frame:attack.startup,type:'spawn_vfx',eventIdTemplate:'{matchId}:{simulationFrame}:{fighterId}:{moveInstance}:{eventIndex}',payload:{socket:'uppercut_fist',candidateOnly:true,visualRole:isCinematic?'surrounding_rising_cyan_gold_aura_not_additional_hit':'single_uppercut_motion_arc_not_additional_hit'}}];
 if(isCinematic&&(aura||redraw))pack.presentationTrack=[]; // Aura pixels belong to source frames, not a runtime spawn.
 pack.presentationSockets=[{id:'uppercut_fist',...c.v2.releaseSocket,mirrorRule:'x_prime_equals_canvas_width_minus_x',eventTypes:['spawn_vfx']}];
 pack.approvalRecords=[uri(approvalPath)];pack.validation={...pack.validation,creativeWarnings:warning,humanApprovalRequired:true};
 pack.transitions=[];pack.transitionCompatibility=[{fromStates:['idle','walk_forward','walk_backward','crouch'],toState:id,condition:'grounded_up_special_input',addsGameplayFrames:false}];
 pack.gameplayTimingStatus={owner:'simulation',state:'sandbox_candidate_awaiting_combat_approval',authoritative:false,candidateValues:{startup:attack.startup,active:attack.active,recovery:attack.recovery,damage:hit.damage},notes:warning};
 write(path.join(out,strength,'animation.package.json'),pack);
}
write(path.join(base,'heaven-splitter-family.candidate.v1.json'),family);write(path.join(root,'public/lamuh-legacy-v2/heaven-splitter-v1/manifest.json'),family);review.heavenSplitterFamily=family;
const first=read(path.join(base,'first-playable.bundle.json'));
for(const s of ['light','medium','heavy']){const id='heaven_splitter_'+s;if(!first.coverage.specials.includes(id))first.coverage.specials.push(id);}
first.additiveForgeBundles=(first.additiveForgeBundles||[]).filter(b=>b.role!=='up_specials').concat({path:'heaven-splitter-packages/heaven-splitter.bundle.json',packageCount:3,role:'up_specials'});
first.humanReviewStatus=status;first.currentReviewGate.status=status;first.technicalStatus='FORWARD_STARRED_PALM_ACCEPTED_HEAVEN_SPLITTER_PLAYABLE_CANDIDATE';
write(path.join(base,'first-playable.bundle.json'),first);review.firstPlayable=first;review.humanReviewStatus=status;write(reviewPath,review);
const pendingPath=path.join(base,'records/first-playable-closure.pending.json'),pending=read(pendingPath);pending.humanReviewStatus=status;pending.activeFamilyReview='heaven_splitter_light_medium_heavy';pending.currentReviewFocus={...pending.currentReviewFocus,...first.currentReviewGate};write(pendingPath,pending);
const bundle={...read(path.join(base,'character.bundle.json')),id:'lamuh_heaven_splitter_v1',displayName:'Lamuh Heaven Splitter candidate',promotionState:'candidate',animationPackages:['light','medium','heavy'].map(s=>s+'/animation.package.json'),packageGroups:{up_specials:['light','medium','heavy'].map(s=>'heaven_splitter_'+s)}};
write(path.join(out,'heaven-splitter.bundle.json'),bundle);write(path.join(root,'generated/manifests/lamuh_heaven_splitter_v1.candidate.runtime.json'),compileFromPath(path.join(out,'heaven-splitter.bundle.json')));
write(path.join(base,'records/heaven-splitter-v1.hash-lock.json'),{candidateOnly:true,deployable:false,sourceSheet:report.sourceSha256,heavySourceSheets:heavy?Object.fromEntries(Object.entries(heavy.families).map(([k,v])=>[k,v.sourceSha256])):null,redrawnAuraSources:redraw?Object.fromEntries(['raw-aura-redraw.png','raw-aura-magenta.png'].map(f=>[f,hash(path.join(path.dirname(redrawReportPath),f))])):null,frames:Object.fromEntries(Object.entries(family.variants).map(([s,c])=>[s,c.v2.frames.map(f=>({publicPath:f.publicPath,sha256:f.sha256}))]))});
if(fs.existsSync(path.join(base,'records/heaven-splitter-v4.approval.json')))require('./mark_lamuh_heaven_splitter_v4').mark();
console.log('Heaven Splitter L/M/H packaged: 36/43/53 ticks, one hit, simulation-owned hop; scoped approval retained when present.');
