const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
const { compileFromPath, stableJson } = require('./production_contracts');
const root = path.resolve(__dirname, '..'), repo = path.resolve(root, '../..');
const base = path.join(root, 'content-source/characters/lamuh-legacy-v2');
const out = path.join(base, 'divine-vanish-medium-packages-v4');
const read = p => JSON.parse(fs.readFileSync(p, 'utf8'));
const hash = p => crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex').toUpperCase();
const uri = p => 'repo://' + path.relative(repo, p).replaceAll('\\', '/');
const holds = [1, 4, 3, 2, 8, 2, 3, 4, 3, 2];
function build({ check = false } = {}) {
  const { fighterDefinitions } = require('../dist/data/fighters');
  const attack = fighterDefinitions.lamuh_legacy_v2.attacks.legacy_divine_vanish_medium;
  assert.deepEqual([attack.startup, attack.active, attack.recovery], [5, 0, 27]);
  assert.deepEqual(attack.hitboxes, []);
  const protectedPaths = [path.join(root, 'public/lamuh-legacy-v2/review-data.json'), path.join(base, 'divine-vanish-family.candidate.v1.json'), path.join(root, 'public/lamuh-legacy-v2/divine-vanish-v3/manifest.json')];
  const protectedHashes = protectedPaths.map(p => [p, hash(p)]);
  const old = read(protectedPaths[1]), medium = structuredClone(old.variants.medium);
  medium.status = 'awaiting_human_divine_vanish_medium_extended_blink_review';
  for (const [key, delta] of [['A', -1], ['B', 0], ['C', 1]]) {
    const exposure = [...holds]; exposure[1] += delta; exposure[7] += delta; exposure[8] += delta;
    medium.timingCandidates[key] = { ...medium.timingCandidates[key], phaseTicks: { startup: 5 + delta, active: 0, recovery: 27 + delta * 2 }, durationTicks: exposure.reduce((a, b) => a + b, 0), exposureTicks: exposure };
  }
  let x = 0;
  medium.v2.authoredWorldRootPath = Array.from({ length: 32 }, (_, tick) => { const segment = attack.rootMotionSegments.find(s => tick >= s.start && tick <= s.end); if (segment) x += segment.velocity; return { x, y: 0 }; });
  assert.equal(x, -180);
  medium.v2.rootMotionTrack.segments = structuredClone(attack.rootMotionSegments);
  medium.v2.visualBlink = { ...medium.v2.visualBlink, window: { start: 10, end: 17 }, durationTicks: 8, travelDuringBlink: 160, vulnerabilityUnchanged: true };
  medium.v2.preservationBoundary.approvedV2Disposition = 'Light, Heavy counter, and all frame source bytes unchanged; Medium duration and retreat explicitly revised by user.';
  medium.reviewNotes = ['Medium extended to32 ticks and180 retreat units; eight invisible ticks carry160 units.', 'Same ten source references; body disappears completely at slot4 then returns as the same whole pose.', 'No invulnerability, teleport, opponent displacement, damage, cancel or meter award added.', 'Previous28-tick110-distance version remains preserved history.'];
  const manifest = { schemaVersion: '1.0.0', candidateOnly: true, deployable: false, status: medium.status, medium };
  const template = read(path.join(base, 'divine-vanish-packages/medium/animation.package.json'));
  const bundle = read(path.join(base, 'character.bundle.json'));
  const approvalPath = path.join(out, 'records/human-review.pending.json'), metadataPath = path.join(out, 'records/registration.json'), provenancePath = path.join(out, 'records/provenance.json');
  const provenance = { ...template.provenance, references: [...template.provenance.references, uri(protectedPaths[1])], revisionChain: [...template.provenance.revisionChain, 'MEDIUM_EXTENDED_VISUAL_BLINK_V4'], humanApproval: { state: 'pending', approvedAt: null, approvedBy: null } };
  const p = structuredClone(template), id = 'divine_vanish_medium_v4';
  p.id = id; p.simulationLength = 32; p.provenance = provenance;
  p.sourceFrames = p.sourceFrames.map((f, index) => ({ ...f, id: `${id}_frame_${index}`, approvalUri: uri(approvalPath), provenanceUri: uri(provenancePath), metadataUri: uri(metadataPath) }));
  for (const f of medium.v2.frames) assert.equal(hash(path.join(root, 'public', f.publicPath)), f.sha256);
  let cursor = 0;
  p.exposures = holds.map((duration, index) => { const e = { sourceFrameId: p.sourceFrames[index].id, start: cursor, duration }; cursor += duration; return e; });
  p.anchors = p.exposures.map(e => ({ frame: e.start, sourceFrameId: e.sourceFrameId, root: medium.v2.root, feet: medium.v2.root, effect: medium.v2.root }));
  p.groundingTrack = p.groundingTrack.map((f, index) => ({ ...f, sourceFrameId: p.sourceFrames[index].id }));
  p.phases.recovery = [{ start: 5, end: 31 }];
  p.combatTrack.recovery = 27; p.combatTrack.rootMotionTrack = medium.v2.rootMotionTrack; p.combatTrack.timingAuthorship.authoredTotalDuration = 32;
  p.transitionCompatibility = p.transitionCompatibility.map(t => ({ ...t, toState: id }));
  p.approvalRecords = [uri(approvalPath)]; p.validation.creativeWarnings = medium.reviewNotes;
  p.gameplayTimingStatus = { ...p.gameplayTimingStatus, candidateValues: { startup: 5, active: 0, recovery: 27, damage: 0, retreatDistance: 180 }, notes: medium.reviewNotes };
  const publish = (file, value) => { if (check) assert.equal(stableJson(read(file)), stableJson(value), `Stale ${file}`); else { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n'); } };
  publish(approvalPath, { state: 'pending', approvedAt: null, approvedBy: null, candidateOnly: true, deployable: false, remainingReview: medium.reviewNotes });
  publish(provenancePath, provenance); publish(metadataPath, manifest);
  publish(path.join(out, 'medium/animation.package.json'), p);
  const bundlePath = path.join(out, 'medium-v4.bundle.json');
  publish(bundlePath, { ...bundle, id: 'lamuh_divine_medium_v4', displayName: 'Lamuh Medium extended blink candidate', animationPackages: ['medium/animation.package.json'], packageGroups: { medium_extended_blink: [id] } });
  publish(path.join(root, 'generated/manifests/lamuh_divine_medium_v4.candidate.runtime.json'), compileFromPath(bundlePath));
  publish(path.join(root, 'public/lamuh-legacy-v2/divine-vanish-medium-v4/manifest.json'), manifest);
  publish(path.join(base, 'divine-vanish-medium.candidate.v4.json'), manifest);
  for (const [file, before] of protectedHashes) assert.equal(hash(file), before, `Protected history changed: ${file}`);
  console.log(`${check ? 'CHECKED' : 'BUILT'} Medium V4:32 ticks,8-tick blink,180 retreat; previous sources/artifacts preserved.`);
}
if (require.main === module) build({ check: process.argv.includes('--check') });
module.exports = { build, holds };
